export const PERMISSIONS = {
    // POS & Sales
    POS_ACCESS: "POS_ACCESS",
    POS_MANAGE_SHIFT: "POS_MANAGE_SHIFT",
    PROCESS_SALE: "PROCESS_SALE",
    REFUND_SALE: "REFUND_SALE",
    VOID_TRANSACTION: "VOID_TRANSACTION",
    APPLY_DISCOUNT: "APPLY_DISCOUNT",

    // Inventory
    MANAGE_INVENTORY: "MANAGE_INVENTORY", // Create Items, GRN, Transfers
    INVENTORY_VIEW: "INVENTORY_VIEW",
    INVENTORY_MANAGE_ITEMS: "INVENTORY_MANAGE_ITEMS",
    INVENTORY_MANAGE_STOCK: "INVENTORY_MANAGE_STOCK",
    VIEW_COST_PRICE: "VIEW_COST_PRICE",

    // Finance & Reports
    VIEW_FINANCE: "VIEW_FINANCE", // P&L, Balance Sheet
    VIEW_REPORTS: "VIEW_REPORTS", // General Reports
    MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",

    // HR & Payroll
    VIEW_PAYROLL: "VIEW_PAYROLL",
    PAYROLL_CREATE: "PAYROLL_CREATE",
    PAYROLL_APPROVE: "PAYROLL_APPROVE", // Formerly APPROVE_PAYROLL
    PAYROLL_PAY: "PAYROLL_PAY",
    MANAGE_EMPLOYEES: "MANAGE_EMPLOYEES",
    HR_MANAGE_TEAMS: "HR_MANAGE_TEAMS",
    HR_VIEW_SENSITIVE: "HR_VIEW_SENSITIVE", // Salaries, Bank Details
    HR_LEAVE_APPROVE: "HR_LEAVE_APPROVE",
    HR_APPRAISAL_REVIEW: "HR_APPRAISAL_REVIEW",

    // Admin
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",

    // Tasks (Granular)
    TASK_VIEW: "TASK_VIEW",
    TASK_CREATE: "TASK_CREATE",
    TASK_EDIT: "TASK_EDIT",
    TASK_DELETE: "TASK_DELETE",
    TASK_ASSIGN: "TASK_ASSIGN",
    TASK_STAGE_MANAGE: "TASK_STAGE_MANAGE"
} as const;

export type Permission = keyof typeof PERMISSIONS;
